# Generated by Django 5.1.6 on 2025-03-12 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
